PROJECT_DELIVERY_FIXTURES = [
    {
        "fixture_id": "project-northstar-portal",
        "scenario_name": "Northstar customer portal phase 1",
        "milestone_name": "Northstar phase-1 customer portal go-live",
        "customer": "Harbor Retail Group",
        "business_context": (
            "Customer portal launch supports a $520K services commitment and replaces a "
            "manual claims workflow before the summer retail peak."
        ),
        "executive_owner": "Nina Alvarez, VP Customer Operations",
        "sprint_name": "Northstar Portal Phase 1",
        "team_size": 4,
        "days_remaining": 10,
        "total_tasks": 18,
        "completed_tasks": 7,
        "velocity_history": [12, 10, 8],
        "remaining_engineering_hours": 238,
        "remaining_story_points": 34,
        "available_engineering_hours": 192,
        "external_dependencies": [
            "Customer SSO metadata approval",
            "Claims export file from operations",
        ],
        "capacity_notes": (
            "Frontend engineer is 80% available; QA is shared with production release support."
        ),
        "delay_cost_per_week_usd": 62000,
        "committed_revenue_usd": 520000,
        "target_date": "2026-07-08",
        "current_date": "2026-06-09",
        "backlog_count": 23,
        "avg_velocity": 9,
        "sprint_length_days": 14,
        "blockers": [
            "SSO metadata has not been approved by customer IT",
            "Claims export sample is missing production edge cases",
        ],
        "capacity_changes": "QA analyst is available 50% until June 17 due to release support.",
        "tasks": [
            {"id": "AUTH-41", "skill": "identity", "estimate_hours": 22, "priority": "HIGH"},
            {"id": "PORTAL-87", "skill": "frontend", "estimate_hours": 30, "priority": "HIGH"},
            {"id": "CLAIMS-54", "skill": "backend", "estimate_hours": 28, "priority": "HIGH"},
            {"id": "QA-218", "skill": "quality", "estimate_hours": 24, "priority": "HIGH"},
            {"id": "OPS-33", "skill": "enablement", "estimate_hours": 14, "priority": "NORMAL"},
            {"id": "OBS-18", "skill": "observability", "estimate_hours": 16, "priority": "NORMAL"},
            {"id": "UAT-12", "skill": "customer-success", "estimate_hours": 18, "priority": "HIGH"},
            {"id": "REL-47", "skill": "release", "estimate_hours": 12, "priority": "NORMAL"},
        ],
        "team_members": [
            {
                "name": "Iris Chen",
                "role": "Full-stack Lead",
                "skills": ["identity", "backend", "frontend"],
                "load_pct": 74,
                "availability_pct": 80,
            },
            {
                "name": "Samir Gupta",
                "role": "Frontend Engineer",
                "skills": ["frontend", "release"],
                "load_pct": 68,
                "availability_pct": 80,
            },
            {
                "name": "Marta Silva",
                "role": "QA Analyst",
                "skills": ["quality", "customer-success"],
                "load_pct": 72,
                "availability_pct": 50,
            },
            {
                "name": "Theo Martin",
                "role": "Backend Engineer",
                "skills": ["backend", "observability", "enablement"],
                "load_pct": 61,
                "availability_pct": 90,
            },
        ],
        "sprint_weeks": 2,
        "avg_task_hours": 22,
        "hourly_rate": 145,
        "timeline_weeks": 4,
        "instruction": (
            "Create a recovery plan for Northstar portal phase 1 with epics for SSO, "
            "claims export, customer UAT, release readiness, named owners, risk tradeoffs, "
            "and executive decision points."
        ),
    },
    {
        "fixture_id": "project-orion-bank-launch",
        "scenario_name": "Orion v4.2 regional bank launch",
        "milestone_name": "Orion v4.2 FirstWest Bank launch",
        "customer": "FirstWest Bank",
        "business_context": (
            "Mobile onboarding launch is tied to $1.25M in contracted digital account "
            "opening revenue and a public branch migration date."
        ),
        "executive_owner": "Maya Patel, SVP Digital Banking",
        "sprint_name": "Orion v4.2 Launch Readiness",
        "team_size": 7,
        "days_remaining": 12,
        "total_tasks": 52,
        "completed_tasks": 23,
        "velocity_history": [24, 21, 18],
        "remaining_engineering_hours": 612,
        "remaining_story_points": 91,
        "available_engineering_hours": 470,
        "external_dependencies": [
            "Identity provider production certificate",
            "Fraud-service rate limit approval",
            "Security exception sign-off",
        ],
        "capacity_notes": (
            "Tech lead is at 60% due to Sev-2 support; QA lead is split with release audit."
        ),
        "delay_cost_per_week_usd": 185000,
        "committed_revenue_usd": 1250000,
        "target_date": "2026-07-18",
        "current_date": "2026-06-09",
        "backlog_count": 58,
        "avg_velocity": 20,
        "sprint_length_days": 14,
        "blockers": [
            "Fraud-service performance test has not passed at target volume",
            "Final SOC2 evidence package is missing two controls",
            "Mobile app release candidate is waiting on bank branding approval",
        ],
        "capacity_changes": "Two engineers are covering production support until June 14.",
        "tasks": [
            {"id": "OIDC-214", "skill": "identity", "estimate_hours": 28, "priority": "HIGH"},
            {"id": "OIDC-219", "skill": "identity", "estimate_hours": 18, "priority": "HIGH"},
            {"id": "FRAUD-88", "skill": "backend", "estimate_hours": 36, "priority": "HIGH"},
            {"id": "FRAUD-91", "skill": "backend", "estimate_hours": 30, "priority": "HIGH"},
            {"id": "SEC-72", "skill": "security", "estimate_hours": 24, "priority": "HIGH"},
            {"id": "SEC-76", "skill": "security", "estimate_hours": 18, "priority": "HIGH"},
            {"id": "QA-140", "skill": "quality", "estimate_hours": 34, "priority": "HIGH"},
            {"id": "QA-143", "skill": "automation", "estimate_hours": 26, "priority": "HIGH"},
            {"id": "MOB-302", "skill": "mobile", "estimate_hours": 32, "priority": "HIGH"},
            {"id": "REL-31", "skill": "release", "estimate_hours": 16, "priority": "NORMAL"},
            {"id": "OBS-44", "skill": "observability", "estimate_hours": 20, "priority": "NORMAL"},
            {
                "id": "UAT-27",
                "skill": "customer-success",
                "estimate_hours": 18,
                "priority": "NORMAL",
            },
        ],
        "team_members": [
            {
                "name": "Asha Rao",
                "role": "Tech Lead",
                "skills": ["identity", "backend", "security"],
                "load_pct": 82,
                "availability_pct": 60,
            },
            {
                "name": "Mateo Cruz",
                "role": "Senior Backend Engineer",
                "skills": ["backend", "release"],
                "load_pct": 68,
                "availability_pct": 85,
            },
            {
                "name": "Lina Park",
                "role": "QA Lead",
                "skills": ["quality", "automation", "security"],
                "load_pct": 76,
                "availability_pct": 70,
            },
            {
                "name": "Devon Shah",
                "role": "Platform Engineer",
                "skills": ["release", "observability", "backend"],
                "load_pct": 55,
                "availability_pct": 90,
            },
            {
                "name": "Camila Torres",
                "role": "Mobile Engineer",
                "skills": ["mobile", "frontend", "quality"],
                "load_pct": 63,
                "availability_pct": 85,
            },
            {
                "name": "Ben Wallace",
                "role": "Security Engineer",
                "skills": ["security", "identity"],
                "load_pct": 70,
                "availability_pct": 75,
            },
            {
                "name": "Rina Okafor",
                "role": "Implementation Manager",
                "skills": ["customer-success", "release", "enablement"],
                "load_pct": 64,
                "availability_pct": 80,
            },
        ],
        "sprint_weeks": 3,
        "avg_task_hours": 24,
        "hourly_rate": 165,
        "timeline_weeks": 6,
        "instruction": (
            "Create a recovery plan for Orion v4.2 launch readiness with epics for "
            "identity, fraud-service readiness, security evidence, mobile release, QA "
            "automation, owners, risk tradeoffs, and executive decision points."
        ),
    },
    {
        "fixture_id": "project-atlas-migration",
        "scenario_name": "Atlas cloud migration cutover",
        "milestone_name": "Summit Energy Atlas migration cutover",
        "customer": "Summit Energy",
        "business_context": (
            "Cloud cutover unlocks $2.4M in contracted analytics capacity for a regulated "
            "energy customer and avoids parallel-run infrastructure charges."
        ),
        "executive_owner": "Ravi Menon, VP Platform Engineering",
        "sprint_name": "Atlas Migration Cutover",
        "team_size": 10,
        "days_remaining": 15,
        "total_tasks": 76,
        "completed_tasks": 31,
        "velocity_history": [31, 28, 23],
        "remaining_engineering_hours": 1118,
        "remaining_story_points": 168,
        "available_engineering_hours": 860,
        "external_dependencies": [
            "Network allowlist approval",
            "Database replication freeze window",
            "Customer DR test window",
            "Security architecture review",
        ],
        "capacity_notes": "Two platform engineers are on incident rotation until June 16.",
        "delay_cost_per_week_usd": 320000,
        "committed_revenue_usd": 2400000,
        "target_date": "2026-07-26",
        "current_date": "2026-06-09",
        "backlog_count": 88,
        "avg_velocity": 26,
        "sprint_length_days": 14,
        "blockers": [
            "Database replication dry run has not met RPO",
            "Customer DR test window is not confirmed",
            "Network allowlist request is waiting on customer security review",
        ],
        "capacity_changes": "Platform team has two engineers on incident rotation.",
        "tasks": [
            {"id": "NET-31", "skill": "network", "estimate_hours": 26, "priority": "HIGH"},
            {"id": "NET-37", "skill": "network", "estimate_hours": 22, "priority": "HIGH"},
            {"id": "DB-82", "skill": "database", "estimate_hours": 42, "priority": "HIGH"},
            {"id": "DB-91", "skill": "database", "estimate_hours": 38, "priority": "HIGH"},
            {"id": "CUT-17", "skill": "platform", "estimate_hours": 34, "priority": "HIGH"},
            {"id": "CUT-23", "skill": "platform", "estimate_hours": 32, "priority": "HIGH"},
            {"id": "DR-22", "skill": "reliability", "estimate_hours": 36, "priority": "HIGH"},
            {"id": "DR-28", "skill": "reliability", "estimate_hours": 30, "priority": "HIGH"},
            {"id": "SEC-118", "skill": "security", "estimate_hours": 28, "priority": "HIGH"},
            {"id": "OBS-09", "skill": "observability", "estimate_hours": 20, "priority": "NORMAL"},
            {"id": "REL-62", "skill": "release", "estimate_hours": 18, "priority": "NORMAL"},
            {"id": "DATA-44", "skill": "analytics", "estimate_hours": 24, "priority": "NORMAL"},
            {"id": "RUN-19", "skill": "enablement", "estimate_hours": 16, "priority": "NORMAL"},
            {
                "id": "UAT-33",
                "skill": "customer-success",
                "estimate_hours": 18,
                "priority": "NORMAL",
            },
        ],
        "team_members": [
            {
                "name": "Ravi Iyer",
                "role": "Platform Lead",
                "skills": ["platform", "observability", "reliability"],
                "load_pct": 78,
                "availability_pct": 65,
            },
            {
                "name": "Mina Chen",
                "role": "Database Engineer",
                "skills": ["database", "backend"],
                "load_pct": 66,
                "availability_pct": 85,
            },
            {
                "name": "Omar Haddad",
                "role": "Network Engineer",
                "skills": ["network", "platform"],
                "load_pct": 82,
                "availability_pct": 70,
            },
            {
                "name": "Grace Lee",
                "role": "Reliability Engineer",
                "skills": ["reliability", "observability"],
                "load_pct": 58,
                "availability_pct": 90,
            },
            {
                "name": "Sofia Kim",
                "role": "Security Architect",
                "skills": ["security", "network"],
                "load_pct": 74,
                "availability_pct": 75,
            },
            {
                "name": "Jonas Weber",
                "role": "Data Platform Engineer",
                "skills": ["analytics", "database", "platform"],
                "load_pct": 67,
                "availability_pct": 85,
            },
            {
                "name": "Maya Brooks",
                "role": "Release Manager",
                "skills": ["release", "enablement"],
                "load_pct": 60,
                "availability_pct": 80,
            },
            {
                "name": "Ethan Price",
                "role": "Implementation Lead",
                "skills": ["customer-success", "release"],
                "load_pct": 58,
                "availability_pct": 85,
            },
            {
                "name": "Leah Stone",
                "role": "Backend Engineer",
                "skills": ["backend", "platform"],
                "load_pct": 64,
                "availability_pct": 90,
            },
            {
                "name": "Akira Sato",
                "role": "SRE",
                "skills": ["reliability", "observability", "platform"],
                "load_pct": 72,
                "availability_pct": 70,
            },
        ],
        "sprint_weeks": 4,
        "avg_task_hours": 28,
        "hourly_rate": 175,
        "timeline_weeks": 8,
        "instruction": (
            "Build an Atlas migration cutover plan with epics for network readiness, "
            "database replication, DR validation, security review, observability, rollback "
            "criteria, owners, and executive decision points."
        ),
    },
    {
        "fixture_id": "project-helios-consent-platform",
        "scenario_name": "Helios healthcare consent platform",
        "milestone_name": "Northlake Health Helios consent go-live",
        "customer": "Northlake Health",
        "business_context": (
            "Consent platform launch protects a $690K healthcare implementation and supports "
            "a regulatory reporting deadline."
        ),
        "executive_owner": "Priya Shah, VP Customer Success",
        "sprint_name": "Helios Consent Platform Release",
        "team_size": 5,
        "days_remaining": 9,
        "total_tasks": 29,
        "completed_tasks": 11,
        "velocity_history": [15, 13, 11],
        "remaining_engineering_hours": 356,
        "remaining_story_points": 53,
        "available_engineering_hours": 280,
        "external_dependencies": [
            "HIPAA audit export approval",
            "Customer legal review for consent language",
            "EHR sandbox access renewal",
        ],
        "capacity_notes": (
            "Security engineer is shared with a compliance audit; QA has one tester out."
        ),
        "delay_cost_per_week_usd": 88000,
        "committed_revenue_usd": 690000,
        "target_date": "2026-07-12",
        "current_date": "2026-06-09",
        "backlog_count": 34,
        "avg_velocity": 13,
        "sprint_length_days": 14,
        "blockers": [
            "EHR sandbox access expires before final regression",
            "Consent language is still under customer legal review",
            "Security test evidence is missing audit export coverage",
        ],
        "capacity_changes": "Security capacity is 60% until the compliance audit is closed.",
        "tasks": [
            {"id": "CONSENT-74", "skill": "frontend", "estimate_hours": 26, "priority": "HIGH"},
            {"id": "CONSENT-81", "skill": "backend", "estimate_hours": 32, "priority": "HIGH"},
            {"id": "AUDIT-22", "skill": "compliance", "estimate_hours": 28, "priority": "HIGH"},
            {"id": "EHR-47", "skill": "integration", "estimate_hours": 30, "priority": "HIGH"},
            {"id": "SEC-144", "skill": "security", "estimate_hours": 22, "priority": "HIGH"},
            {"id": "QA-231", "skill": "quality", "estimate_hours": 26, "priority": "HIGH"},
            {"id": "DOC-64", "skill": "enablement", "estimate_hours": 12, "priority": "NORMAL"},
            {"id": "REL-88", "skill": "release", "estimate_hours": 14, "priority": "NORMAL"},
            {
                "id": "OBS-71",
                "skill": "observability",
                "estimate_hours": 16,
                "priority": "NORMAL",
            },
        ],
        "team_members": [
            {
                "name": "Nora Ali",
                "role": "Product Engineer",
                "skills": ["frontend", "backend"],
                "load_pct": 70,
                "availability_pct": 80,
            },
            {
                "name": "Julian Reed",
                "role": "Integration Engineer",
                "skills": ["integration", "backend"],
                "load_pct": 73,
                "availability_pct": 85,
            },
            {
                "name": "Mei Lin",
                "role": "Compliance Analyst",
                "skills": ["compliance", "enablement"],
                "load_pct": 78,
                "availability_pct": 75,
            },
            {
                "name": "Hector Diaz",
                "role": "Security Engineer",
                "skills": ["security", "observability"],
                "load_pct": 80,
                "availability_pct": 60,
            },
            {
                "name": "Tara Evans",
                "role": "QA Engineer",
                "skills": ["quality", "release"],
                "load_pct": 66,
                "availability_pct": 70,
            },
        ],
        "sprint_weeks": 3,
        "avg_task_hours": 22,
        "hourly_rate": 158,
        "timeline_weeks": 5,
        "instruction": (
            "Create a recovery plan for Helios consent platform with epics for consent UX, "
            "EHR integration, audit exports, security evidence, QA regression, owners, and "
            "executive decision points."
        ),
    },
]
