REVENUE_OPS_FIXTURES = [
    {
        "fixture_id": "account-meridian",
        "account_name": "Meridian Healthcare",
        "account_arr": 84000,
        "contract_end_date": "2026-09-30",
        "days_to_renewal": 117,
        "login_frequency_30d": 42,
        "feature_adoption_score": 7.8,
        "support_tickets_90d": 3,
        "nps_score": 72,
        "last_csm_touchpoint": "2026-05-15",
        "upsell_conversations": 1,
    },
    {
        "fixture_id": "account-fortis",
        "account_name": "Fortis Logistics",
        "account_arr": 36000,
        "contract_end_date": "2026-08-15",
        "days_to_renewal": 71,
        "login_frequency_30d": 8,
        "feature_adoption_score": 4.2,
        "support_tickets_90d": 11,
        "nps_score": 31,
        "last_csm_touchpoint": "2026-04-01",
        "upsell_conversations": 0,
        "login_trend": "declining 62% over 60 days",
        "adoption_trend": "stalled - no new features activated in 45 days",
        "competitor_mentions": 2,
    },
    {
        "fixture_id": "rep-sarah-chen",
        "rep_name": "Sarah Chen",
        "quota_target": 500000,
        "quarter_close_date": "2026-06-30",
        "days_remaining": 26,
        "historical_close_rate": 0.62,
        "avg_sales_cycle_days": 45,
        "pipeline_deals": [
            {
                "account": "Meridian Healthcare",
                "arr": 84000,
                "stage": "Negotiation",
                "probability": 0.85,
            },
            {
                "account": "Fortis Logistics",
                "arr": 62000,
                "stage": "Proposal Sent",
                "probability": 0.45,
            },
        ],
    },
]
