REVENUE_OPS_FIXTURES = [
    {
        "fixture_id": "revenue-acme-save-motion",
        "scenario_name": "Q2 revenue save motion",
        "business_context": (
            "Sales leadership needs a single view of renewal risk, churn signals, and "
            "recoverable late-quarter pipeline before the Monday forecast call."
        ),
        "executive_owner": "Daniel Kim, Chief Revenue Officer",
        "account_name": "Acme Financial",
        "account_arr": 900000,
        "renewal_arr_usd": 900000,
        "expansion_arr_usd": 260000,
        "segment": "Enterprise Financial Services",
        "contract_end_date": "2026-09-30",
        "days_to_renewal": 113,
        "login_frequency_30d": 18,
        "feature_adoption_score": 5.7,
        "support_tickets_90d": 14,
        "nps_score": 4,
        "last_csm_touchpoint": "2026-05-08",
        "upsell_conversations": 0,
        "historical_save_rate": 0.42,
        "churn_account_name": "Acme Financial",
        "churn_account_arr": 900000,
        "login_trend": "finance admin usage down 38% over 30 days",
        "adoption_trend": "invoice automation flat, reporting exports increasing",
        "ticket_sentiment": "negative",
        "exec_engagement": "economic buyer missed two QBRs and delegated renewal call",
        "competitor_mentions": 3,
        "contract_downloads": 2,
        "early_intervention_value": 0.45,
        "account_owner": "Jordan Lee",
        "csm_owner": "Rhea Morgan",
        "exec_sponsor": "Daniel Kim",
        "rep_name": "Jordan Lee",
        "quota_target": 1800000,
        "closed_to_date_usd": 620000,
        "commit_pipeline_usd": 430000,
        "best_case_pipeline_usd": 1060000,
        "quarter_close_date": "2026-06-30",
        "days_remaining": 21,
        "historical_close_rate": 0.31,
        "avg_sales_cycle_days": 52,
        "pipeline_deals": [
            {
                "account": "Helio Manufacturing",
                "arr": 520000,
                "crm_probability": 0.62,
                "stage": "Legal review",
                "close_plan": "redline turnaround due Friday",
                "risk": "procurement owner on PTO",
                "next_step": "VP Sales to confirm signing authority",
            },
            {
                "account": "Beacon Health",
                "arr": 410000,
                "crm_probability": 0.44,
                "stage": "Security review",
                "close_plan": "security questionnaire pending",
                "risk": "SOC2 exception requested",
                "next_step": "Security lead to join customer call",
            },
            {
                "account": "Koru Energy",
                "arr": 360000,
                "crm_probability": 0.35,
                "stage": "Business case",
                "close_plan": "ROI case not signed by CFO",
                "risk": "budget approval moved to July",
                "next_step": "RevOps to rebuild value case with usage data",
            },
            {
                "account": "Northport Insurance",
                "arr": 280000,
                "crm_probability": 0.28,
                "stage": "Solution validation",
                "close_plan": "claims automation pilot results due next week",
                "risk": "pilot sponsor has not confirmed success criteria",
                "next_step": "AE and SE to complete pilot scorecard",
            },
        ],
    },
    {
        "fixture_id": "revenue-meridian-fortis",
        "scenario_name": "Meridian and Fortis renewal risk",
        "business_context": (
            "Stable healthcare renewal can be protected while logistics churn risk needs "
            "an executive save play."
        ),
        "executive_owner": "Priya Shah, VP Customer Success",
        "account_name": "Meridian Healthcare",
        "account_arr": 840000,
        "renewal_arr_usd": 840000,
        "expansion_arr_usd": 180000,
        "segment": "Enterprise Healthcare",
        "contract_end_date": "2026-09-30",
        "days_to_renewal": 113,
        "login_frequency_30d": 42,
        "feature_adoption_score": 7.8,
        "support_tickets_90d": 3,
        "nps_score": 72,
        "last_csm_touchpoint": "2026-05-15",
        "upsell_conversations": 1,
        "historical_save_rate": 0.38,
        "churn_account_name": "Fortis Logistics",
        "churn_account_arr": 360000,
        "login_trend": "declining 62% over 60 days",
        "adoption_trend": "dispatch automation stalled; no new features activated in 45 days",
        "ticket_sentiment": "negative",
        "exec_engagement": "economic buyer has not attended the last two check-ins",
        "competitor_mentions": 2,
        "contract_downloads": 1,
        "early_intervention_value": 0.5,
        "account_owner": "Sarah Chen",
        "csm_owner": "Luis Ortega",
        "exec_sponsor": "Priya Shah",
        "rep_name": "Sarah Chen",
        "quota_target": 1250000,
        "closed_to_date_usd": 390000,
        "commit_pipeline_usd": 640000,
        "best_case_pipeline_usd": 920000,
        "quarter_close_date": "2026-06-30",
        "days_remaining": 21,
        "historical_close_rate": 0.54,
        "avg_sales_cycle_days": 45,
        "pipeline_deals": [
            {
                "account": "Meridian Healthcare",
                "arr": 640000,
                "crm_probability": 0.82,
                "stage": "Negotiation",
                "close_plan": "legal addendum with customer counsel",
                "risk": "data processing addendum open",
                "next_step": "legal team to complete DPA edits",
            },
            {
                "account": "Fortis Logistics",
                "arr": 310000,
                "crm_probability": 0.42,
                "stage": "Proposal sent",
                "close_plan": "revised pricing proposal requested",
                "risk": "buyer is comparing logistics workflow competitor",
                "next_step": "CSM and AE to run adoption recovery workshop",
            },
            {
                "account": "UrbanCare Clinics",
                "arr": 280000,
                "crm_probability": 0.48,
                "stage": "Business case",
                "close_plan": "clinical ROI case due next week",
                "risk": "CFO has not approved implementation budget",
                "next_step": "RevOps to provide benchmark ROI model",
            },
        ],
    },
    {
        "fixture_id": "revenue-enterprise-west",
        "scenario_name": "Enterprise West pipeline recovery",
        "business_context": (
            "Large expansion and renewal motions need account-level focus before quarter close."
        ),
        "executive_owner": "Maya Singh, VP Enterprise Sales West",
        "account_name": "Apex Industrial",
        "account_arr": 1250000,
        "renewal_arr_usd": 1250000,
        "expansion_arr_usd": 520000,
        "segment": "Enterprise Manufacturing",
        "contract_end_date": "2026-10-15",
        "days_to_renewal": 128,
        "login_frequency_30d": 21,
        "feature_adoption_score": 5.1,
        "support_tickets_90d": 9,
        "nps_score": 28,
        "last_csm_touchpoint": "2026-04-29",
        "upsell_conversations": 0,
        "historical_save_rate": 0.44,
        "churn_account_name": "Beacon Health",
        "churn_account_arr": 640000,
        "login_trend": "admin usage down 41% over 30 days",
        "adoption_trend": "automation usage down, reporting exports increasing",
        "ticket_sentiment": "mixed",
        "exec_engagement": "new sponsor has not accepted QBR invite",
        "competitor_mentions": 4,
        "contract_downloads": 3,
        "early_intervention_value": 0.48,
        "account_owner": "Maya Singh",
        "csm_owner": "Anika Rao",
        "exec_sponsor": "Daniel Kim",
        "rep_name": "Maya Singh",
        "quota_target": 2200000,
        "closed_to_date_usd": 510000,
        "commit_pipeline_usd": 720000,
        "best_case_pipeline_usd": 1360000,
        "quarter_close_date": "2026-06-30",
        "days_remaining": 21,
        "historical_close_rate": 0.28,
        "avg_sales_cycle_days": 58,
        "pipeline_deals": [
            {
                "account": "Apex Industrial",
                "arr": 720000,
                "crm_probability": 0.52,
                "stage": "Legal review",
                "close_plan": "master services agreement in redlines",
                "risk": "indemnity clause blocked by legal",
                "next_step": "CRO to approve fallback liability position",
            },
            {
                "account": "Beacon Health",
                "arr": 640000,
                "crm_probability": 0.39,
                "stage": "Security review",
                "close_plan": "security evidence package requested",
                "risk": "customer CISO asked for pen-test evidence",
                "next_step": "Security team to join executive sponsor call",
            },
            {
                "account": "Lumina Retail",
                "arr": 380000,
                "crm_probability": 0.31,
                "stage": "Business case",
                "close_plan": "store operations ROI review",
                "risk": "rollout budget shifted to next quarter",
                "next_step": "AE to narrow scope to top 40 stores",
            },
            {
                "account": "Cascadia Foods",
                "arr": 260000,
                "crm_probability": 0.24,
                "stage": "Technical validation",
                "close_plan": "integration architecture review not scheduled",
                "risk": "customer technical sponsor changed roles",
                "next_step": "SE manager to secure new technical sponsor",
            },
        ],
    },
    {
        "fixture_id": "revenue-public-sector-renewal",
        "scenario_name": "Public sector renewal and expansion",
        "business_context": (
            "A state agency renewal is stable, but expansion depends on procurement timing "
            "and executive sponsor coverage."
        ),
        "executive_owner": "Priya Shah, VP Customer Success",
        "account_name": "StateWorks Digital",
        "account_arr": 720000,
        "renewal_arr_usd": 720000,
        "expansion_arr_usd": 310000,
        "segment": "Public Sector",
        "contract_end_date": "2026-09-20",
        "days_to_renewal": 103,
        "login_frequency_30d": 55,
        "feature_adoption_score": 8.1,
        "support_tickets_90d": 4,
        "nps_score": 64,
        "last_csm_touchpoint": "2026-05-22",
        "upsell_conversations": 2,
        "historical_save_rate": 0.52,
        "churn_account_name": "Metro Transit Authority",
        "churn_account_arr": 480000,
        "login_trend": "dispatcher usage down 33% over 45 days",
        "adoption_trend": "mobile incident workflow stalled after pilot",
        "ticket_sentiment": "mixed",
        "exec_engagement": (
            "operations sponsor changed roles and replacement is not onboarded"
        ),
        "competitor_mentions": 1,
        "contract_downloads": 2,
        "early_intervention_value": 0.42,
        "account_owner": "Elliot Park",
        "csm_owner": "Mina Joseph",
        "exec_sponsor": "Priya Shah",
        "rep_name": "Elliot Park",
        "quota_target": 1600000,
        "closed_to_date_usd": 540000,
        "commit_pipeline_usd": 520000,
        "best_case_pipeline_usd": 980000,
        "quarter_close_date": "2026-06-30",
        "days_remaining": 21,
        "historical_close_rate": 0.46,
        "avg_sales_cycle_days": 61,
        "pipeline_deals": [
            {
                "account": "StateWorks Digital",
                "arr": 510000,
                "crm_probability": 0.74,
                "stage": "Procurement",
                "close_plan": "final purchase order routed to agency finance",
                "risk": "procurement committee meets only twice before quarter close",
                "next_step": "VP Public Sector to confirm committee agenda",
            },
            {
                "account": "Metro Transit Authority",
                "arr": 380000,
                "crm_probability": 0.36,
                "stage": "Pilot review",
                "close_plan": "incident workflow pilot scorecard under review",
                "risk": "new operations sponsor has not accepted success criteria",
                "next_step": "CSM to run sponsor onboarding with pilot results",
            },
            {
                "account": "Civic Water District",
                "arr": 260000,
                "crm_probability": 0.43,
                "stage": "Security review",
                "close_plan": "security packet returned with open encryption question",
                "risk": "security review may slip to July",
                "next_step": "Security lead to answer encryption exception by Thursday",
            },
            {
                "account": "County Health Network",
                "arr": 220000,
                "crm_probability": 0.31,
                "stage": "Business case",
                "close_plan": "grant-funded business case awaiting CFO sign-off",
                "risk": "grant approval is outside seller control",
                "next_step": "RevOps to split grant-dependent scope from base purchase",
            },
        ],
    },
]
